#!/bin/bash

# Nexa-Sphere Environment Setup Script
# This script helps configure the .env.local file with Stripe keys

echo "==============================================="
echo "   Nexa-Sphere Environment Configuration"
echo "==============================================="
echo ""
echo "This script will help you set up your Stripe API keys."
echo "You can find these keys in your Stripe Dashboard."
echo ""

# Function to prompt for input
# Usage: prompt_key "Variable Name" "Human Readable Description" "Default Value (optional)"
prompt_key() {
    local var_name=$1
    local description=$2
    local default_val=$3
    local input_val

    echo -n "Enter $description"
    if [ -n "$default_val" ]; then
        echo -n " [$default_val]"
    fi
    echo ": "
    read input_val

    if [ -z "$input_val" ] && [ -n "$default_val" ]; then
        input_val=$default_val
    fi
    
    # Export for current session (optional) and append/replace in file
    # Here we just construct the content to write
    eval "$var_name=\"$input_val\""
}

# 1. Stripe Secret Key
echo "--- API Configuration ---"
prompt_key "STRIPE_SECRET_KEY" "Stripe Secret Key (sk_test_... or sk_live_...)"

# 2. Stripe Publishable Key
prompt_key "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" "Stripe Publishable Key (pk_test_... or pk_live_...)"

echo ""
echo "--- Product Price IDs (Services Page) ---"
echo "Create these products in Stripe and copy the Price ID (price_...)"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_STARTER" "Price ID for 'AI Launch Starter'"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_GROWTH" "Price ID for 'AI Growth Accelerator'"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_DOMINATOR" "Price ID for 'AI Market Dominator'"

echo ""
echo "--- Product Price IDs (Agency Offer Page) ---"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_AGENCY_IGNITE" "Price ID for 'Social Ignite' ($120)"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_AGENCY_GROWTH" "Price ID for 'Agency Growth' ($350)"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_AGENCY_DOMINATOR" "Price ID for 'Market Dominator' ($1500)"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_AGENCY_ELITE" "Price ID for 'SV Elite System' ($2500)"

echo ""
echo "--- Product Price IDs (Nexaclean Pro) ---"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_CORE" "Price ID for 'Core System' ($3000)"
prompt_key "NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_FULL" "Price ID for 'Full System + AI' ($5000)"

# Write to .env.local
ENV_FILE=".env.local"

# Backup existing .env.local
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.bak"
    echo "Backed up existing $ENV_FILE to $ENV_FILE.bak"
fi

echo ""
echo "Writing validation to $ENV_FILE..."

cat > "$ENV_FILE" <<EOL
# Generated by setup_env.sh

# Stripe API Keys
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Services Page Products
NEXT_PUBLIC_STRIPE_PRICE_STARTER=$NEXT_PUBLIC_STRIPE_PRICE_STARTER
NEXT_PUBLIC_STRIPE_PRICE_GROWTH=$NEXT_PUBLIC_STRIPE_PRICE_GROWTH
NEXT_PUBLIC_STRIPE_PRICE_DOMINATOR=$NEXT_PUBLIC_STRIPE_PRICE_DOMINATOR

# Agency Offer Page Products
NEXT_PUBLIC_STRIPE_PRICE_AGENCY_IGNITE=$NEXT_PUBLIC_STRIPE_PRICE_AGENCY_IGNITE
NEXT_PUBLIC_STRIPE_PRICE_AGENCY_GROWTH=$NEXT_PUBLIC_STRIPE_PRICE_AGENCY_GROWTH
NEXT_PUBLIC_STRIPE_PRICE_AGENCY_DOMINATOR=$NEXT_PUBLIC_STRIPE_PRICE_AGENCY_DOMINATOR
NEXT_PUBLIC_STRIPE_PRICE_AGENCY_ELITE=$NEXT_PUBLIC_STRIPE_PRICE_AGENCY_ELITE

# Nexaclean Pro Page Products
NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_CORE=$NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_CORE
NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_FULL=$NEXT_PUBLIC_STRIPE_PRICE_NEXACLEAN_FULL

# Base URL (Adjust if deploying to production)
NEXT_PUBLIC_BASE_URL=http://localhost:3000
EOL

echo "==============================================="
echo "   Configuration Complete!"
echo "==============================================="
echo "1. Your keys have been saved to $ENV_FILE"
echo "2. Please RESTART your development server (Ctrl+C, then 'npm run dev') for changes to take effect."
echo "==============================================="
